[package]
name = "forza_telem"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
iced = "0.13.0"
local-ip-address = "0.6.1"
slint = "1.5.1"

[build-dependencies]
slint-build = "1.5.1"
